language: c

git:
  depth: false

cache:
  directories:
    - ~/arduino_ide

install:
  - make setup

env:
  global:
    - THIS_BUILD_TAG=`git describe --tags`

# base configs
_deploy_s3: &deploy_s3
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  acl: public_read
  bucket: opentrons-modules-builds
  dot_match: true
  on:
    all_branches: true

jobs:
  include:
    - stage: deploy
      name: Branch build
      if: tag IS blank
      script:
        - make build
        - make zip-all
      before_deploy:
        - make clean
      deploy:
        - # upload all branch artifacts to S3
          <<: *deploy_s3
          local_dir: ./build
          upload_dir: modules-$THIS_BUILD_TAG-$TRAVIS_BRANCH

    - stage: deploy
      name: Release build
      if: tag IS present
      script:
        - make build
      before_deploy:
        - source set_release_vars.sh
      deploy:
        - # upload module release artifacts to S3
          <<: *deploy_s3
          local_dir: $RELEASE_LOCAL_DIR
          upload-dir: $RELEASE_UPLOAD_DIR

notifications:
  email:
    on_success: change
    on_failure: change
