language: python

cache:
  directories:
    - ~/arduino_ide

install:
  - make setup

script:
  - make build

deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: opentrons-modules-builds
  skip_cleanup: true
  local_dir: build/thermo-cycler
  upload-dir: thermocycler
  on:
    branch: repo_CI-and-deployment

notifications:
  email:
    on_success: change
    on_failure: change
