language: c

git:
  depth: false

cache:
  directories:
    - ./arduino_ide
    - ~/.arduino15
    - ./stm32-tools

dist: focal

addons:
  apt:
    sources:
      - sourceline: 'deb https://apt.kitware.com/ubuntu/ focal main'
        key_url: 'https://apt.kitware.com/keys/kitware-archive-latest.asc'
    packages:
      - cmake
      - gcc-10

# base configs
_deploy_s3: &deploy_s3
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  acl: public_read
  bucket: opentrons-modules-builds
  dot_match: true
  on:
    all_branches: true

jobs:
  include:
    - name: deploy build
      script:
        # https://travis-ci.community/t/install-cmake-using-apt-again/4062 is why this uses
        # /usr/local/bin explicitly
        - /usr/bin/cmake --preset=arduino .
        - /usr/bin/cmake --build ./build-arduino --target zip-all
        - /usr/bin/cmake --install ./build-arduino
      before_deploy:
        - source ./scripts/set_build_vars.sh
      deploy:
        - # upload module release artifacts to S3
          <<: *deploy_s3
          local_dir: $RELEASE_LOCAL_DIR
          upload_dir: $RELEASE_UPLOAD_DIR
    - name: build STM32 module firmware
      script:
        - /usr/bin/cmake --preset=stm32-cross . -DCMAKE_BUILD_TYPE=MinSizeRel
        - /usr/bin/cmake --build ./build-stm32-cross --target heater-shaker
        - /usr/bin/cmake --build ./build-stm32-cross --target heater-shaker-format-ci
        - /usr/bin/cmake --build ./build-stm32-cross --target heater-shaker-lint
    - name: build STM32 module libs as host and run tests
      script:
        - /usr/bin/cmake --preset=stm32-host .
        - /usr/bin/cmake --build ./build-stm32-host --target build-and-test
