language: c

git:
  depth: false

cache:
  directories:
    - ./arduino_ide

install:
  - sudo apt remove --purge --auto-remove cmake
  - wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | gpg --dearmor - | sudo tee /etc/apt/trusted.gpg.d/kitware.gpg >/dev/null
  - sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
  - sudo apt update
  - sudo apt install cmake

# base configs
_deploy_s3: &deploy_s3
  provider: s3
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-2
  acl: public_read
  bucket: opentrons-modules-builds
  dot_match: true
  on:
    all_branches: true

jobs:
  include:
    - stage: deploy
      name: deploy build
      script:
        - cmake --preset=arduino .
        - cmake --build ./build --target zip-all
        - cmake --install ./build
      before_deploy:
        - source ./scripts/set_build_vars.sh
      deploy:
        - # upload module release artifacts to S3
          <<: *deploy_s3
          local_dir: $RELEASE_LOCAL_DIR
          upload_dir: $RELEASE_UPLOAD_DIR

notifications:
  email:
    on_success: change
    on_failure: change
