# This file is part of CMake-codecov.
#
# Copyright (c)
#   2015-2020 RWTH Aachen University, Federal Republic of Germany
#
# See the LICENSE file in the package base directory for details
#
# Written by Alexander Haase, alexander.haase@rwth-aachen.de
#

language: c

matrix:
  include:
    - os: linux
      dist: xenial
      compiler: gcc
    - os: linux
      dist: xenial
      compiler: clang

    - os: linux
      dist: bionic
      compiler: gcc
    - os: linux
      dist: bionic
      compiler: clang

    - os: osx
      compiler: clang


addons:
  apt:
    packages:
      - cmake
      - lcov
      - gfortran


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
      brew update --quiet >& /dev/null;
    fi
  # The following solution was inspired by http://stackoverflow.com/a/20802381
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]];
    then
      for pkg in gcc cmake lcov; do
        if brew list -1 | grep -q "^${pkg}\$"; then
          brew outdated $pkg || brew upgrade $pkg;
        else
          brew install $pkg;
        fi
      done
    fi

script:
  - mkdir build && cd build
  - cmake .. -DENABLE_COVERAGE=On && make && make test gcov lcov

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
