name: 'Thermocycler Refresh build/test'
on:
  pull_request:
    paths:
      - 'stm32-modules/thermocycler-refresh/**/*'
      - 'stm32-modules/common/**/*'
      - 'stm32-modules/include/common/**/*'
      - 'stm32-modules/include/thermocycler-refresh/**/*'
      - 'cmake/**/*'
      - 'CMakeLists.txt'
      - 'stm32-modules/CMakeLists.txt'
      - 'CMakePresets.json'
      - '.clang-format'
      - '.clang-tidy'
    paths_ignore:
      - 'cmake/Arduino*'
  push:
    paths:
      - 'stm32-modules/thermocycler-refresh/**/*'
      - 'stm32-modules/common/**/*'
      - 'stm32-modules/include/common/**/*'
      - 'stm32-modules/include/thermocycler-refresh/**/*'
      - 'cmake/**/*'
      - 'CMakeLists.txt'
      - 'stm32-modules/CMakeLists.txt'
      - 'CMakePresets.json'
      - '.clang-format'
      - '.clang-tidy'
      - '.github/workflows/thermocycler-refresh.yaml'
    paths_ignore:
      - 'cmake/Arduino*'
    branches:
      - '*'
    tags:
      - 'thermocycler-refresh@*'
  workflow_dispatch:


defaults:
  run:
    shell: bash


jobs:
  cross-compile-check:
    name: 'Cross-Compile/Check'
    runs-on: 'ubuntu-20.04'
    timeout-minutes: 10
    steps:
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - uses: 'actions/cache@v2'
        with:
          key: stm32-cross-${{ secrets.MODULES_STM32_CACHE_VERSION }}-${{ hashFiles('cmake/*') }}
          restore-keys: stm32-cross-${{ secrets.MODULES_STM32_CACHE_VERSION }}-
          path: './stm32-tools'
      - name: 'Configure'
        run: cmake --preset=stm32-cross .
      - name: 'Format'
        run: cmake --build ./build-stm32-cross --target thermocycler-refresh-format-ci
      - name: 'Lint'
        run: cmake --build ./build-stm32-cross --target thermocycler-refresh-lint
      - name: 'Build'
        run: cmake --build ./build-stm32-cross --target thermocycler-refresh-hex
  host-compile-test:
    name: 'Host-Compile/Test'
    runs-on: 'ubuntu-20.04'
    timeout-minutes: 10
    env:
      CC: gcc-10
      CXX: g++-10
    steps:
      - run: |
          sudo apt update
          sudo apt install gcc-10 g++-10
      - uses: 'actions/checkout@v2'
        with:
          fetch-depth: 0
      - uses: 'actions/cache@v2'
        with:
          path: './stm32-tools'
          key: stm32-host-${{ secrets.MODULES_STM32_CACHE_VERSION }}-${{ hashFiles('cmake/*') }}
          restore-keys: stm32-host-${{ secrets.MODULES_STM32_CACHE_VERSION }}-
      - name: 'Configure'
        run: cmake --preset=stm32-host .
      - name: 'Build Simulator'
        run: cmake --build ./build-stm32-host --target thermocycler-refresh-simulator
      - name: 'Build and Test'
        run: cmake --build ./build-stm32-host --target thermocycler-refresh-build-and-test
